spring.application.name=backend

# JWT
spring.datasource.url=jdbc:mysql://localhost:3306/bowling_turni_db
spring.datasource.username=bowling_user
spring.datasource.password=Madovevai.96
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=bowling-turni-secret-key-molto-lunga-almeno-32-caratteri
jwt.expiration=86400000

server.port=8081
